# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "vade-mecum"
version = "0.1.0"
entrypoint = "src/template.typ"
authors = ["<@jinhXY>"]
license = "Unlicense"
description = "My personal master template/package for all things Typst"
homepage = ""
repository = "https://github.com/jinhXY/typst-vade-mecum"
keywords = []
categories = []
disciplines = []
compiler = "0.15.1"
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
